### ISSUE TITLE
Probably erroneous display in the user interface.

### ISSUE THREAD

**Issue by khunchan** [nazar-pc/space-acres#35]
![image](https://github.com/nazar-pc/space-acres/assets/46874357/a0019461-bdf1-4e8a-adbd-8cf0efb71988)
After rebooting and achieving synchronization, the farm waits more than 2 hours for synchronization.

Made a change of address for the reward, specifying a zero-balance address. If the error is only in the display, the balance will start to increase. I will add the information later.

**Comment by nazar-pc** [comment]
I suspect the reason is that you are fully plotted and not replotting is necessary, thus plotting state never changes from `PlottingState::Unknown` to `PlottingState::Idle`. We should probably fire an event in https://github.com/subspace/subspace in case initial plotting is not necessary such that subscribers like Space Acres can catch it and change plotting state to `PlottingState::Idle`.

Farming should still happen in background unless farmer is doing initial plotting.

**Comment by khunchan** [comment]
![image](https://github.com/nazar-pc/space-acres/assets/46874357/37a481a7-5f6d-43ba-a468-5889ec9b3e86)
After 3 hours of waiting, the status changed. Coins are not mined yet, we will wait.

**Comment by khunchan** [comment]
Works stable, coins are mined.
