### ISSUE TITLE
I'm testing it on Windows 11, version 0.0.16. I'm experiencing network problems during block synchronization.

### ISSUE THREAD

**Issue by wampirx** [nazar-pc/space-acres#84]
Hello, as far as I can see, when synchronizing the node, it crashes the entire network and internet, and the internet of the modem and other devices connected to the network is cut off.When I control it, this error is fixed when farming starts, and for example, when the node is closed and it starts synchronizing again, the network crashes again and the same problem continues until it is synchronized.

**Comment by nazar-pc** [comment]
Can you share more details about your network? It is recommended to use wired Ethernet connection (many Wi-Fi access really struggle under load) and at least 10 Mbps upload/download, ideally 100 Mbps+ for peak usage.

**Comment by wampirx** [comment]
Hello again, of course, I can share, first of all, I have more than 1 laptop, all of them have the same problem, network features, wired ethernet connection, 1 GB port and wifi, to do tests and I still have the same problem, my modem internet speed is 100 mpbs, computer features are Intel i5 and i7 and i9 (18 and 24). and 32 )cpu 64 gb ram 3 computer features and lastly, all of them have Samsung 2 TB nvme ssd.

**Comment by nazar-pc** [comment]
My educated guess would be that it is not Internet as such or the laptop, it is probably Wi-Fi part of the router that is the bottleneck here. If you have ability, try to organize wired connection between router and laptop, otherwise maybe consider router upgrade to something more performant.

I'm not sure there is much that can be done in Space Acres to dramatically improve situation, especially with multiple machines in local network.
